# Generated by Django 3.2 on 2021-04-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adhaar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adhar',
            table='Adhar',
        ),
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
    ]
